In [18]:
import pandas as pd
df = pd.read_csv("customers.csv")
df.head()

,customer_id,signup_date,country,age,gender,loyalty_tier,acquisition_channel
0,1,2021-04-08,BR,48,Male,Bronze,Referral
1,2,2023-04-28,IN,36,Female,Silver,Organic
2,3,2022-12-18,UK,35,Female,Silver,Organic
3,4,2022-04-26,US,45,Male,Silver,Paid Search
4,5,2022-04-20,IN,53,Male,Silver,Organic

In [19]:
df.shape

(100000, 7)

In [20]:
df.columns

Index(['customer_id', 'signup_date', 'country', 'age', 'gender',
       'loyalty_tier', 'acquisition_channel'],
      dtype='object')

In [21]:
df.isnull().sum()

customer_id            0
signup_date            0
country                0
age                    0
gender                 0
loyalty_tier           0
acquisition_channel    0
dtype: int64

In [22]:
transactions = pd.read_csv("transactions.csv")
transactions.shape

(103127, 9)

In [23]:
import pandas as pd
customers = pd.read_csv("customers.csv")
campaigns = pd.read_csv("campaigns.csv")
transactions = pd.read_csv("transactions.csv")
products = pd.read_csv("products.csv")
customers.head()
campaigns.head()
transactions.head()
products.head()
print("customers:", customers.shape)
print("campaigns:", campaigns.shape)
print("transactions:", transactions.shape)
print("products:", products.shape)

customers: (100000, 7)
campaigns: (50, 7)
transactions: (103127, 9)
products: (2000, 6)

In [24]:
print(customers.columns.tolist())
print(campaigns.columns.tolist())
print(transactions.columns.tolist())
print(products.columns.tolist())
print(customers.isnull().sum())
print(campaigns.isnull().sum())
print(transactions.isnull().sum())
print(products.isnull().sum())

['customer_id', 'signup_date', 'country', 'age', 'gender', 'loyalty_tier', 'acquisition_channel']
['campaign_id', 'channel', 'objective', 'start_date', 'end_date', 'target_segment', 'expected_uplift']
['transaction_id', 'timestamp', 'customer_id', 'product_id', 'quantity', 'discount_applied', 'gross_revenue', 'campaign_id', 'refund_flag']
['product_id', 'category', 'brand', 'base_price', 'launch_date', 'is_premium']
customer_id            0
signup_date            0
country                0
age                    0
gender                 0
loyalty_tier           0
acquisition_channel    0
dtype: int64
campaign_id        0
channel            0
objective          0
start_date         0
end_date           0
target_segment     0
expected_uplift    0
dtype: int64
transaction_id          0
timestamp               0
customer_id             0
product_id          10449
quantity                0
discount_applied        0
gross_revenue       10449
campaign_id             0
refund_flag             0
dtype: int64
product_id     0
category       0
brand          0
base_price     0
launch_date    0
is_premium     0
dtype: int64

Convert date columns

In [25]:
customers["signup_date"] = pd.to_datetime(customers["signup_date"], errors="coerce")
campaigns["start_date"] = pd.to_datetime(campaigns["start_date"], errors="coerce")
campaigns["end_date"] = pd.to_datetime(campaigns["end_date"], errors="coerce")
transactions["timestamp"] = pd.to_datetime(transactions["timestamp"], errors="coerce")
products["launch_date"] = pd.to_datetime(products["launch_date"], errors="coerce")

In [26]:
transactions_clean = transactions[transactions["refund_flag"] == 0].copy()
transactions_clean.shape

(100098, 9)

In [27]:
merged = transactions_clean.merge(customers, on="customer_id", how="left")
merged = merged.merge(products, on="product_id", how="left")
merged = merged.merge(campaigns, on="campaign_id", how="left")
merged.head()

,transaction_id,timestamp,customer_id,product_id,quantity,discount_applied,gross_revenue,campaign_id,refund_flag,signup_date,...,brand,base_price,launch_date,is_premium,channel,objective,start_date,end_date,target_segment,expected_uplift
0,1,2021-12-27 08:25:15,59540,1630.0,3,0.00,43.74,0,0,2021-11-26,...,Brand_76,14.58,2022-11-02,0.0,NaN,NaN,NaT,NaT,NaN,NaN
1,2,2023-06-06 21:14:26,54871,1901.0,3,0.00,174.78,21,0,2021-06-24,...,Brand_20,58.26,2022-09-21,0.0,Email,Acquisition,2023-02-21,2023-03-27,Churn Risk,0.090
2,3,2023-08-31 05:29:54,51818,1884.0,1,0.00,40.61,37,0,2021-07-17,...,Brand_23,40.61,2021-04-24,0.0,Paid Search,Cross-sell,2022-10-20,2022-12-01,Deal Seekers,0.096
3,4,2022-06-26 20:33:46,18164,1114.0,2,0.15,68.76,13,0,2022-01-30,...,Brand_19,40.45,2021-05-26,0.0,Display,Reactivation,2022-03-19,2022-06-09,Churn Risk,0.063
4,5,2023-07-26 18:12:35,86915,408.0,1,0.00,14.64,4,0,2023-06-15,...,Brand_39,14.64,2022-01-08,0.0,Display,Reactivation,2022-07-25,2022-10-07,Deal Seekers,0.111

In [28]:
events_chunks = pd.read_csv("events.csv", chunksize=100000)

In [29]:
events_first = next(events_chunks)
events_first.head()

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,session_duration_sec,experiment_group
0,1,2021-01-14 13:35:43,43812,535101,view,1004.0,desktop,Email,43,PLP,115.1,Control
1,2,2021-12-03 21:36:50,71340,96426,add_to_cart,986.0,desktop,Email,10,PDP,32.4,Variant_A
2,3,2021-12-27 08:25:15,59540,220126,purchase,1630.0,mobile,Organic,0,PDP,190.7,Variant_A
3,4,2022-01-22 15:06:54,3601,484555,add_to_cart,1532.0,desktop,Paid Search,30,Checkout,134.8,Variant_B
4,5,2021-05-10 12:03:09,92735,60646,bounce,NaN,desktop,Email,26,PLP,53.1,Variant_A

In [30]:
events_preview = pd.read_csv("events.csv", nrows=5)
events_preview
events_preview.columns
events_chunks = pd.read_csv("events.csv", chunksize=100000)
events_first = next(events_chunks)
events_first.head()
events_first.shape
events_first.isnull().sum()

event_id                   0
timestamp                  0
customer_id                0
session_id                 0
event_type                 0
product_id              9952
device_type             2045
traffic_source             0
campaign_id                0
page_category              0
session_duration_sec       0
experiment_group           0
dtype: int64

In [31]:
events_small = pd.read_csv(
    "events.csv",
    usecols=["customer_id", "timestamp", "campaign_id", "event_type"],
    chunksize=100000
)
first_small = next(events_small)
first_small.head()

             timestamp  customer_id   event_type  campaign_id
0  2021-01-14 13:35:43        43812         view           43
1  2021-12-03 21:36:50        71340  add_to_cart           10
2  2021-12-27 08:25:15        59540     purchase            0
3  2022-01-22 15:06:54         3601  add_to_cart           30
4  2021-05-10 12:03:09        92735       bounce           26

In [32]:
events_first["timestamp"] = pd.to_datetime(events_first["timestamp"], errors="coerce")
events_first["timestamp"].head()

0   2021-01-14 13:35:43
1   2021-12-03 21:36:50
2   2021-12-27 08:25:15
3   2022-01-22 15:06:54
4   2021-05-10 12:03:09
Name: timestamp, dtype: datetime64[ns]

In [33]:
events_first["event_type"].value_counts()
events_chunks = pd.read_csv("events.csv", chunksize=20000)
events_first = next(events_chunks)
events_first.head()

,event_id,timestamp,customer_id,session_id,event_type,product_id,device_type,traffic_source,campaign_id,page_category,session_duration_sec,experiment_group
0,1,2021-01-14 13:35:43,43812,535101,view,1004.0,desktop,Email,43,PLP,115.1,Control
1,2,2021-12-03 21:36:50,71340,96426,add_to_cart,986.0,desktop,Email,10,PDP,32.4,Variant_A
2,3,2021-12-27 08:25:15,59540,220126,purchase,1630.0,mobile,Organic,0,PDP,190.7,Variant_A
3,4,2022-01-22 15:06:54,3601,484555,add_to_cart,1532.0,desktop,Paid Search,30,Checkout,134.8,Variant_B
4,5,2021-05-10 12:03:09,92735,60646,bounce,NaN,desktop,Email,26,PLP,53.1,Variant_A